sudo: required
services:
  - docker

before_install:
  - docker build -t bernardocaputo/bank -f Dockerfile.dev .

script:
  - MIX_ENV=test mix ecto.create
  - MIX_ENV=test mix ecto.migrate
  - docker run -it bernardocaputo/bank mix test