sudo: required

language: elixir
elixir:
  - '1.7.4'
otp_release:
  - '20.0'
services:
  - docker
  - postgresql

before_install:
  - mix local.hex --force
  - mix local.rebar --force
  - mix deps.get
  - MIX_ENV=test mix ecto.create
  - MIX_ENV=test mix ecto.migrate

script:
  - mix test