version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports: 
      - 4000:4000
    expose:
      - "80"
    volumes:
      - .:/app
      - /app/deps
      - /app/_build
    depends_on:
      - postgres   
    environment:
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
      DB_NAME: bank_prod
      MIX_ENV: prod
  postgres:
    image: postgres:10
    restart: always
    volumes: 
      - db-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
  web:
    build: .
    links:
      - app
    ports:
      - "80:80"
volumes: 
  db-data:
    driver: local
