version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports: 
      - 4000:4000
    volumes:
      - /Users/caputo/Documents/workspace/bank/deps
      - .:/app
    depends_on:
      - postgres   
  postgres:
    image: postgres:10
    restart: always
    volumes: 
      - db-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
volumes: 
  db-data:
    driver: local
